import type { Cookie } from "@/types"

export const COOKIES: Cookie[] = [
  {
    id: "cc",
    slug: "chocolate-chip-toffee",
    name: "Chocolate Chip Toffee",
    symbol: "Cc",
    atomicNumber: 1,
    group: "classic",
    description: "The classic, elevated. Buttery toffee bits meet perfectly melty chocolate chips.",
    price: 4.50,
    isActive: true,
    isUnstable: false,
    imageUrl: "/images/cookies/CCT2jpeg.jpeg",
  },
  {
    id: "pbo",
    slug: "peanut-butter-oreo",
    name: "Peanut Butter Oreo",
    symbol: "PbO",
    atomicNumber: 2,
    group: "classic",
    description: "Creamy peanut butter dough loaded with Oreo pieces. Dangerously addictive.",
    price: 5.00,
    isActive: true,
    isUnstable: false,
    imageUrl: "/images/cookies/pbomenu.jpg",
  },
  {
    id: "bp",
    slug: "banana-pudding",
    name: "Banana Pudding",
    symbol: "BP",
    atomicNumber: 3,
    group: "classic",
    description: "Banana pudding in cookie form. Soft, creamy, and nostalgic in every bite.",
    price: 4.75,
    isActive: true,
    isUnstable: false,
    imageUrl: "/images/cookies/bpmenu.jpg",
  },
  {
    id: "su",
    slug: "sugar-cookie",
    name: "Sugar Cookie",
    symbol: "Su",
    atomicNumber: 4,
    group: "classic",
    description: "The pure formula. Soft, buttery, and impossibly simple — in the best way.",
    price: 3.75,
    isActive: true,
    isUnstable: false,
    imageUrl: "/images/cookies/scmenu.jpg",
  },
  {
    id: "dc",
    slug: "double-chocolate-chunk",
    name: "Double Chocolate Chunk",
    symbol: "Dc",
    atomicNumber: 5,
    group: "classic",
    description: "Rich cocoa dough, double-loaded with chocolate chunks. Maximum chocolate density.",
    price: 4.75,
    isActive: true,
    isUnstable: false,
    imageUrl: "/images/cookies/dcc2.jpg",
  },
  {
    id: "sn",
    slug: "snowball",
    name: "Snowball",
    symbol: "Sn",
    atomicNumber: 6,
    group: "classic",
    description: "Crumbly, powdered perfection. Melts on your tongue like a tiny edible snowfall.",
    price: 4.00,
    isActive: true,
    isUnstable: false,
    imageUrl: "/images/cookies/sb1.jpg",
  },
  // ── Seasonal — Coming Soon ────────────────────────────────────────────────
  {
    id: "ocs",
    slug: "orange-cranberry-sugar",
    name: "Orange Cranberry Sugar",
    symbol: "OcS",
    atomicNumber: 7,
    group: "seasonal",
    description: "A festive twist on the classic — bright citrus zest and tart cranberry folded into a soft, buttery sugar cookie base.",
    price: 4.75,
    isActive: false,
    isUnstable: true,
  },
  {
    id: "mcl",
    slug: "mint-choc-oatmeal-lace",
    name: "Mint Choc Oatmeal Lace",
    symbol: "Mc",
    atomicNumber: 8,
    group: "seasonal",
    description: "A delicate oatmeal lace cookie infused with cool mint and rich chocolate. Crispy edges, complex formula.",
    price: 4.75,
    isActive: false,
    isUnstable: true,
  },
  {
    id: "sma",
    slug: "strawberry-matcha",
    name: "Strawberry Matcha",
    symbol: "SM",
    atomicNumber: 9,
    group: "seasonal",
    description: "Earthy ceremonial matcha meets sweet strawberry in a soft, chewy cookie with a beautiful natural color.",
    price: 4.75,
    isActive: false,
    isUnstable: true,
  },
]

// Color map by group — periodic table tile colors
export const GROUP_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  classic:  { bg: "bg-[#4DAEEA]/10", border: "border-[#4DAEEA]", text: "text-[#4DAEEA]" },
  seasonal: { bg: "bg-[#FF9F43]/10", border: "border-[#FF9F43]", text: "text-[#FF9F43]" },
  custom:   { bg: "bg-[#FF3DA0]/10", border: "border-[#FF3DA0]", text: "text-[#FF3DA0]" },
  limited:  { bg: "bg-[#3EC9C9]/10", border: "border-[#3EC9C9]", text: "text-[#3EC9C9]" },
}
